name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - 
      name: Check Out Repo 
      uses: actions/checkout@v2
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}    
    - 
      shell: bash
      run: tag=date +%s
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./pytorch
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pytorch-pipeline:$tag
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
